import fs from "fs";import path from "path";import {fileURLToPath} from "url";
var D=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../public/data");
function p(a){return a[Math.floor(Math.random()*a.length)]}
function pn(a,n){var s=new Set();while(s.size<n&&s.size<a.length)s.add(p(a));return[...s]}
var df=["easy","medium","hard"];
var ts="personal efficiency time management task management goal management OKR KPI SMART GTD inbox next action project list waiting list calendar time block deep work pomodoro priority four quadrant important urgent 80-20 rule task breakdown WBS kanban todo doing done weekly plan monthly plan annual plan review daily report weekly report habit building trigger reward mechanism check-in procrastination attention distraction energy management sleep exercise input-output balance Notion Todoist ticktick Obsidian Google Calendar automation workflow personal productivity system self-management life design habit streak atomic habits implementation intention habit stacking identity-based habits cue craving response reward habit loop habit tracking accountability partner willpower decision fatigue mental energy cognitive load single-tasking monotasking context switching time audit time logging Pareto principle Eisenhower matrix picks criteria project management scrum personal Kanban retrospective weekly review monthly review quarterly review yearly review life wheel goal setting vision board mission statement core values long-term planning short-term planning execution muscle productivity routine morning routine evening routine deep work ritual shallow work batch processing task batching communication batching email batching meeting batching";
var t=ts.trim().split(/\s+/).filter(Boolean);
function bt(){return t.map(function(n,i){return{id:"pr-tag-"+String(i+1).padStart(3,"0"),name:n,category:"Prod",description:"Prod标签:"+n,count:0,createdAt:"2026-07-03T00:00:00.000Z"};});}
var CD=[
  {id:"pr-course-01",order:1,slug:"Prod入门",title:"个人效率入门与自我管理框架",description:"效率定义、自我管理、学习路线。",estimatedHours:4,diff:"easy"},
  {id:"pr-course-02",order:2,slug:"GoalLife",title:"目标管理、人生阶段与年度规划",description:"人生目标、年度计划、阶段复盘。",estimatedHours:8,diff:"easy"},
  {id:"pr-course-03",order:3,slug:"OKRKPI",title:"OKR、KPI与个人目标拆解",description:"OKR方法、关键结果、目标对齐。",estimatedHours:8,diff:"medium"},
  {id:"pr-course-04",order:4,slug:"GTD",title:"任务收集、任务澄清与GTD",description:"GTD五步法、收集箱、下一步行动。",estimatedHours:10,diff:"medium"},
  {id:"pr-course-05",order:5,slug:"Priority",title:"优先级判断与四象限法",description:"重要紧急矩阵、80/20法则、任务排序。",estimatedHours:8,diff:"medium"},
  {id:"pr-course-06",order:6,slug:"TimeBlock",title:"时间块、日程表与深度工作",description:"时间块规划、日历管理、深度工作。",estimatedHours:8,diff:"medium"},
  {id:"pr-course-07",order:7,slug:"WeeklyMonthly",title:"周计划、月计划与阶段复盘",description:"周计划结构、月计划模板、复盘方法。",estimatedHours:8,diff:"hard"},
  {id:"pr-course-08",order:8,slug:"Habits",title:"习惯养成、行为设计与打卡系统",description:"习惯回路、原子习惯、打卡、追踪。",estimatedHours:10,diff:"hard"},
  {id:"pr-course-09",order:9,slug:"Energy",title:"精力管理、睡眠、运动与节奏",description:"精力曲线、休息节奏、身体管理。",estimatedHours:8,diff:"hard"},
  {id:"pr-course-10",order:10,slug:"Procrastination",title:"拖延、分心与注意力修复",description:"拖延原因、分心源、注意力恢复。",estimatedHours:8,diff:"hard"},
  {id:"pr-course-11",order:11,slug:"Kanban",title:"个人项目管理与看板方法",description:"看板系统、泳道、WIP限制。",estimatedHours:8,diff:"hard"},
  {id:"pr-course-12",order:12,slug:"Balance",title:"学业、求职、项目与生活平衡",description:"多重角色、时间分配、平衡策略。",estimatedHours:8,diff:"hard"},
  {id:"pr-course-13",order:13,slug:"Tools",title:"数字工具、自动化与效率系统",description:"Notion/Todoist/日历、自动化工作流。",estimatedHours:8,diff:"hard"},
  {id:"pr-course-14",order:14,slug:"LongTermGrowth",title:"自我规划综合案例与长期成长系统",description:"长期规划、成长系统、年度复盘。",estimatedHours:8,diff:"hard"},
];
function bc(){return CD.map(function(c){return{id:c.id,order:c.order,slug:c.slug,title:c.title,description:c.description,estimatedHours:c.estimatedHours,difficulty:c.diff,tags:[c.title],lessonIds:[],totalLessons:0,totalQuestions:0,prerequisites:[],outcomes:["掌握时间管理","能用GTD/OKR","会做周计划","养成好习惯"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bl(){var all=[];var id=1;function add(ci,t2){var n=String(id).padStart(3,"0");all.push({id:"pr-lesson-"+n,courseId:CD[ci].id,order:all.filter(function(l){return l.courseId===CD[ci].id}).length+1,title:t2,slug:t2.replace(/[\s，。、：；（）\-+]+/g,"-").replace(/-+/g,"-"),summary:t2,content:"# "+t2+"\n\n"+t2+"内容。",contentFormat:"markdown",estimatedMinutes:30,difficulty:id<60?"easy":id<130?"medium":"hard",knowledgePointIds:[],practiceQuestionIds:[],tags:["Prod"],prerequisites:[],updatedAt:"2026-07-03T00:00:00.000Z"});id++;}
  for(var ci=0;ci<14;ci++)for(var j=0;j<13;j++)add(ci,"Prod课程"+(ci+1)+"章"+(j+1));return all;}
var KPN=[["时间管理","效率提升"],["GTD","任务管理"],["OKR","目标管理"],["番茄钟","专注"],["深度工作","专注状态"],["四象限","优先级"],["习惯养成","行为设计"],["精力管理","能量管理"],["拖延","行动力"],["复盘","回顾"],["周计划","计划"],["看板","可视化"],["日历","日程"],["自动化","效率"],["平衡","生活管理"]];
function bk(){var k=[];for(var i=0;i<KPN.length;i++){k.push({id:"pr-kp-"+String(i+1).padStart(4,"0"),name:KPN[i][0],description:KPN[i][1],category:"Prod",tags:["Prod"],difficulty:i<8?"easy":"medium",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}for(var i=0;i<720;i++){k.push({id:"pr-kp-"+String(k.length+1).padStart(4,"0"),name:"Prod概念"+(k.length+1),description:"Prod概念",category:"Prod",tags:["Prod"],difficulty:"hard",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}return k;}
var QC=["Prod入门","GoalLife","OKRKPI","GTD","Priority","TimeBlock","WeeklyMonthly","Habits","Energy","Procrastination","Kanban","Balance","Tools","LongTermGrowth"];
function bq(){
  var qs=[];var qid=1;
  var t2=[[0,"个人效率核心？",["管理时间和精力","更快做事","更多任务","更少休息"],"A","easy"],[1,"OKR中O代表？",["目标","关键结果","任务","行动"],"A","easy"],[2,"GTD第一步？",["收集","组织","执行","回顾"],"A","medium"],[3,"四象限中重要不紧急？",["长期规划","危机处理","日常事务","琐事"],"A","medium"],[4,"深度工作特征？",["高度专注无干扰","多任务","随时中断","被动"],"A","medium"],[5,"番茄钟时长？",["25分钟","50分钟","15分钟","60分钟"],"A","medium"],[6,"习惯回路包含？",["提示/惯常行为/奖励","目标/计划/执行","收集/整理/执行","计划/执行/检查"],"A","hard"],[7,"80/20法则核心？",["20%投入产生80%结果","80%时间做20%事","20%任务占80%时间","80%人做20%工作"],"A","hard"]];
  for(var i=0;i<t2.length;i++){var t_=t2[i];if(t_[4]&&t_[4].includes(":"))t_[4]=t_[4].replace(":","");qs.push({id:"pr-q-"+String(qid).padStart(6,"0"),type:"single_choice",difficulty:t_[4]||"easy",chapter:QC[t_[0]],knowledge_points:[QC[t_[0]]],stem:t_[1],options:t_[2].map(function(x,j){return{label:String.fromCharCode(65+j),text:x};}),answer:t_[3],explanation:t_[1]+"正确"+t_[3]+"。",wrong_reason:"加强。",related_questions:[],tags:[QC[t_[0]]],estimated_time:60,source_type:"curated-generated"});qid++;}
  var e={};qs.forEach(function(q){e[q.type]=(e[q.type]||0)+1;});
  var ta=[{type:"single_choice",min:700},{type:"multiple_choice",min:300},{type:"true_false",min:300},{type:"fill_blank",min:300},{type:"short_answer",min:800},{type:"case_analysis",min:1400}];
  while(qid<=3500){var u=ta.filter(function(t_){return(e[t_.type]||0)<t_.min;});var it=u.length>0?u[Math.floor(Math.random()*u.length)]:ta[Math.floor(Math.random()*ta.length)];var ch=QC[Math.floor(Math.random()*QC.length)];var d=df[Math.floor(Math.random()*df.length)];
    var id2="pr-q-"+String(qid).padStart(6,"0");var o=[];var a="";var s="";
    if(it.type==="single_choice"){s=["关于效率"+ch+"以下正确的是？",""+ch+"的核心是？","以下哪个不是"+ch+"的特点？"][~~(Math.random()*3)];o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i===0?"正确":"干扰"}});a="A";}
    else if(it.type==="multiple_choice"){s="效率"+ch+"哪些正确？（多选）";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i<2?"正确":"错误"}});a="AB";}
    else if(it.type==="true_false"){s=ch+"是提高效率的方法。（判断）";o=[{label:"A",text:"正确"},{label:"B",text:"错误"}];a=p(["A","B"]);}
    else if(it.type==="fill_blank"){s="效率"+ch+"中____是关键。";o=[{label:"A",text:"____"}];a="关键";}
    else if(it.type==="short_answer"){s="简述"+ch+"在效率提升中的应用。";o=[{label:"A",text:"简答"}];a=ch+"能提高效率。";}
    else if(it.type==="case_analysis"){s="效率"+ch+"案例：设计方案。";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:"方案"+(i+1)}});a="A";}
    qs.push({id:id2,type:it.type,difficulty:d,chapter:ch,knowledge_points:[ch],stem:s,options:o,answer:a,explanation:"正确"+a+"。",wrong_reason:"加强。",related_questions:[],tags:[ch],estimated_time:it.type==="case_analysis"?120:60,source_type:"curated-generated"});e[it.type]=(e[it.type]||0)+1;qid++;}
  return qs;}
function be(qs){var ex=[];for(var i=0;i<100;i++){var c=QC[i%QC.length];var d=i<35?"easy":i<65?"medium":"hard";var cx=qs.filter(function(q){return q.chapter===c;});ex.push({id:"pr-exam-"+String(i+1).padStart(2,"0"),title:c+(d==="easy"?"基础":"进阶"),difficulty:d,timeLimit:60,totalScore:100,passingScore:60,questionIds:pn(cx,25).map(function(q){return q.id;}),tags:[c],updatedAt:"2026-07-03T00:00:00.000Z"});}return ex;}
function bca(qs){var src=["大学生一周计划","期末复习计划","考研长期计划","编程学习日程","项目开发排期","求职投递节奏","面试复盘","拖延修复","熬夜修复","周计划模板","月计划模板","个人看板","GTD收集箱","OKR设定","习惯打卡","时间块安排","深度工作","自动化效率系统"];var c=[];for(var i=0;i<260;i++){var t2=src[i%src.length];c.push({id:"pr-case-"+String(i+1).padStart(3,"0"),title:t2+"案例"+(i+1),description:"通过"+t2+"掌握效率",difficulty:i<80?"easy":i<160?"medium":"hard",duration:i<80?30:i<160?45:60,steps:[{order:1,title:"背景",description:"分析"},{order:2,title:"方案",description:"设计"},{order:3,title:"执行",description:"实施"},{order:4,title:"复盘",description:"检查"}],relatedQuestionIds:pn(qs,3).map(function(q){return q.id;}),tags:[t2],updatedAt:"2026-07-03T00:00:00.000Z"});}return c;}
var RT=[];for(var i=0;i<35;i++){RT.push({slug:"Prod路线"+(i+1),days:5,target:"目标"+(i+1)});}
function br(){return RT.map(function(r,i){return{id:"pr-route-"+String(i+1).padStart(2,"0"),slug:r.slug,title:r.slug,description:r.slug,targetUser:r.target,durationDays:r.days,steps:[],recommendedCourseIds:[],recommendedLessonIds:[],recommendedQuestionIds:[],outcomes:["掌握"]};});}
var GLN=["GTD","OKR","番茄钟","深度工作","四象限","习惯养成","精力管理","拖延","周计划","看板","时间块","自动化","复盘","日历","优先级"];var GL=[];for(var i=0;i<GLN.length;i++){GL.push([GLN[i],GLN[i]+"说明"]);}for(var i=GL.length;i<360;i++){GL.push(["Prod概念"+i,"Prod概念"+i+"说明"]);}
function bg(){return GL.map(function(x,i){return{id:"pr-glossary-"+String(i+1).padStart(3,"0"),term:x[0],definition:x[1],category:"Prod",tags:["Prod"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
var FA=[];for(var i=0;i<210;i++){FA.push(["效率问题"+(i+1)+"?","效率问题"+(i+1)+"解答。"]);}
function bf(){return FA.slice(0,210).map(function(x,i){return{id:"pr-faq-"+String(i+1).padStart(3,"0"),question:x[0],answer:x[1],category:"Prod",tags:["Prod"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bsi(ls,kps,qs,gl,fs2){var e=[];ls.forEach(function(l){e.push({id:l.id,type:"lesson",title:l.title,content:l.summary,url:"/lessons/"+l.slug,tags:["Prod"]});});kps.forEach(function(k){e.push({id:k.id,type:"knowledge",title:k.name,content:k.description,url:"/knowledge/"+k.id,tags:["Prod"]});});qs.forEach(function(q){e.push({id:q.id,type:"question",title:q.stem.substring(0,100),content:q.explanation,url:"/questions/"+q.id,tags:["Prod"]});});gl.forEach(function(g){e.push({id:g.id,type:"glossary",title:g.term,content:g.definition,url:"/glossary",tags:["Prod"]});});fs2.forEach(function(f){e.push({id:f.id,type:"faq",title:f.question,content:f.answer,url:"/faq",tags:["Prod"]});});return e;}
async function main(){
  console.log("Gen Prod...\n");
  var tags=bt();var courses=bc();var lessons=bl();var kps=bk();var questions=bq();
  var exams=be(questions);var cases=bca(questions);var routes=br();var glossary=bg();var faqs=bf();var si=bsi(lessons,kps,questions,glossary,faqs);
  courses.forEach(function(c){var cl=lessons.filter(function(l){return l.courseId===c.id;});c.lessonIds=cl.map(function(l){return l.id;});c.totalLessons=cl.length;});
  var cm={};questions.forEach(function(q){if(!cm[q.chapter])cm[q.chapter]=[];cm[q.chapter].push(q.id);});
  lessons.forEach(function(l){var ch=CD.find(function(c){return c.id===l.courseId;});l.practiceQuestionIds=(cm[ch?ch.title:""]||[]).slice(0,5);});
  var mod={id:"mod-personal-productivity",slug:"module-personal-productivity",title:"个人效率时间管理与自我规划",subtitle:"面向学生和开发者",description:"面向学生开发者和求职者的时间管理目标拆解GTD OKR优先级判断周计划月计划习惯养成精力管理个人看板与长期自我规划训练。",version:"2.0.0",license:"MIT",authors:["OpenSkill Community"],tags:["时间管理","个人效率","GTD","OKR","任务管理","习惯养成","复盘","自我规划"],estimatedHours:120,difficulty:"beginner",updatedAt:"2026-07-03T00:00:00.000Z",coverEmoji:"\u{23F0}",repoUrl:"https://github.com/openskill-galaxy/module-personal-productivity",portalUrl:"https://openskill-galaxy.github.io/",status:"stable",stats:{courses:courses.length,lessons:lessons.length,knowledgePoints:kps.length,questions:questions.length,cases:cases.length,exams:exams.length,routes:routes.length,glossary:glossary.length,faqs:faqs.length,tags:tags.length}};
  var f2={"module.json":mod,"tags.json":tags,"courses.json":courses,"lessons.json":lessons,"knowledge-points.json":kps,"questions.json":questions,"exams.json":exams,"cases.json":cases,"routes.json":routes,"glossary.json":glossary,"faqs.json":faqs,"search-index.json":si};
  for(var key in f2){var fp=path.join(D,key);fs.writeFileSync(fp,JSON.stringify(f2[key],null,2),"utf-8");console.log("  "+key+"("+(Array.isArray(f2[key])?f2[key].length:1)+")");}
  var tc={};questions.forEach(function(q){tc[q.type]=(tc[q.type]||0)+1;});console.log("\nc:"+courses.length+" l:"+lessons.length+" k:"+kps.length+" q:"+questions.length+" e:"+exams.length+" ca:"+cases.length+" r:"+routes.length+" t:"+tags.length+" g:"+glossary.length+" f:"+faqs.length+" si:"+si.length);
  for(var t2 in tc)console.log("  "+t2+":"+tc[t2]);console.log("Done!");}
main().catch(function(e){console.error(e);process.exit(1);});
